version: '3.7'
services:
  django:
    build: ./django
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    volumes:
      - ${PROJECT_ROOT_DIR}:/project
    expose:
      - 8000
    networks:
      translator-app:
        aliases:
          - django
    env_file: .env

  nuxt:
    build: ./nuxt
    depends_on:
      - django
    expose:
      - 3000
    networks:
      translator-app:
        aliases:
          - nuxt

  socket-io:
    build: ./socket-io
    ports:
    - "4000:4000"
    networks:
      translator-app:
        aliases:
          - socket-io

  haproxy:
    build: ./haproxy
    ports:
      - "80:80"
      - "10001:10001" #haproxy stats page
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - nuxt
      - django
    networks:
      translator-app:
        aliases:
          - balancer

  db:
    image: postgres:13
    hostname: db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres=${POSTGRES_DB}
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432" #TODO: remove when task is completed
    networks:
      translator-app:
        aliases:
          - db

volumes:
  database:
    name: database

networks:
  translator-app: