version: '3.7'
services:
  django:
    build: ./django
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    volumes:
      - ${PROJECT_ROOT_DIR}:/project
    networks:
      translator-app:
        aliases:
          - django
    env_file: .env
    ports:
      - "8000:8000"

  db:
    image: postgres:13
    hostname: db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres=${POSTGRES_DB}
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      translator-app:
        aliases:
          - db

volumes:
  database:
    name: database

networks:
  translator-app: