# Generated by Django 3.2.4 on 2021-08-16 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('origin', models.TextField(help_text='Origin text to translate')),
                ('translation', models.TextField(help_text='translation variant')),
                ('translator_comment', models.TextField(blank=True, null=True)),
                ('deadline', models.DateTimeField(null=True)),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'new'), (1, 'in progress'), (2, 'needs_qa'), (3, 'completed')], db_index=True, default=0)),
                ('assigned_qa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_translations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('translator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
