# Generated by Django 3.2.4 on 2021-08-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translation',
            old_name='translator_comment',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='translation',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'new'), (1, 'in progress'), (2, 'needs_qa'), (3, 'verifying'), (4, 'completed')], db_index=True, default=0),
        ),
    ]
